menu:
    # HOME: /
    # ARCHIVE: /archive/
    BLOG: /tags/
    ABOUT: /about/
    SEARCH: /search/

favicon: /favicon.png
logo: /favicon.png

# Comment
gitalk:
    enable: true
    owner: jackliu234
    repo: jackliu234.github.io
    client_id: 4ec287ddd4ac34ff5087
    client_secret: ae45426765f12ac3e2f903662b8938dc4881f703

# Google Analytics
ga: UA-133275176-1

# Copyright Infomation
startyear: 2019

mathjax:
  enable: true
